added optout study action args
mozilla-extensions/normandy-devtools pull request #109
Opened 2020-04-24 17:43 UTC by tiftran

2020-04-28 03:04 UTC, rehandalal requested changes
good stuff! couple little tweaks and this is good to go!

2020-04-28 03:04 UTC, rehandalal commented on extension/content/utils/normandyApi.js
> +  async fetchAllExtensions() {
🎉

2020-04-28 03:04 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/fields/InputField.js
> +  componentClass = "input",
i think what might be easier than this is to forward all the extra props through to the the `Input`.

So here it would be:
```js
export default function InputField({
  label,
  name,
  changeSideEffect,
  ...props
}) {
```

2020-04-28 03:04 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/fields/InputField.js
> +      />
And here it would be:
```js
<Input
  value={data.arguments[name]}
  onChange={handleChange}
  {...props}
/>
```

2020-04-28 03:04 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/OptOutStudy.js
> +}
you should just be able to reuse the existing `SelectField` component with a side effect

2020-04-28 04:40 UTC, rehandalal requested changes
small nits

2020-04-28 04:40 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/OptOutStudy.js
> +  const extensionChangeSideEffect = ({ value }) => {
nit: `extensionApiIdChangeSideEffect`

2020-04-28 04:40 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/OptOutStudy.js
> +  const options = extensions.map((extension) => ({
nit: newline. not sure why eslint isn't complaining about this.

2020-04-28 04:40 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/OptOutStudy.js
> +    <Grid fluid>
Making this a `<FormGroup>` will fix the styling issues.

2020-04-28 06:05 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/OptOutStudy.js
> +  }, []);
See: https://github.com/mozilla-extensions/normandy-devtools/pull/113/files#diff-436b1db721b074d7c034f080f51a31d7R16-R27

You need this effect applied any time the environment key changes.

2020-04-28 07:22 UTC, rehandalal approved these changes
bors r+

2020-04-28 07:27 UTC, rehandalal commented
#112 added in some typescript checks so you'll need to merge master and add `// @ts-nocheck` to the top of the files that have issues

2020-04-28 23:12 UTC, rehandalal commented
bors r+

2020-04-29 00:45 UTC, rehandalal commented
bors retry

2020-04-29 04:41 UTC, rehandalal commented
bors retry

2020-04-29 04:48 UTC, rehandalal commented
@escapewindow any idea why the lint/test etc aren't happening on these bors commits?

2020-04-29 16:37 UTC, escapewindow commented
Do the bors pushes change anything, or do they cherry-pick a changeset from a different branch? I intentionally added code to only rebuild / retest xpis that have changed. If they've already built and tested, a push won't rebuild unless something new changes. This was to encourage people to add multiple xpis in a single repo.

2020-04-29 16:53 UTC, rehandalal commented
@escapewindow bors creates a merge commit in a staging branch where it basically merges the PR commits into HEAD from master and validates that all the tests pass there.

2020-04-29 17:03 UTC, escapewindow commented
@rehandalal I'll try to figure out what's going on. If it was a no-change push, but we need bors to be special-cased, I can see if that's possible.

2020-04-29 19:35 UTC, rehandalal commented
bors retry

🤞🏽

2020-04-29 19:37 UTC, merged