Remove the taskcluster folder
mozilla-extensions/normandy-devtools pull request #153
Opened 2020-05-01 23:11 UTC by rehandalal

/cc @escapewindow to make sure i didn't miss anything.

r?

2020-05-01 23:14 UTC, escapewindow commented
@rehandalal you'll need to re-copy over https://github.com/mozilla-extensions/xpi-template/blob/master/.taskcluster.yml to support cloning xpi-template for the taskcluster source, and populate [xpiSigningType](https://github.com/mozilla-extensions/xpi-template/blob/master/.taskcluster.yml#L19) to enable dep-signing on push/PR.

2020-05-01 23:16 UTC, escapewindow requested changes
https://github.com/mozilla-extensions/normandy-devtools/pull/153#issuecomment-622606651

2020-05-02 00:28 UTC, escapewindow approved these changes

2020-05-04 17:25 UTC, mythmon approved these changes

2020-05-04 17:25 UTC, mythmon commented on .taskcluster.yml
> +          xpiSigningType: "privileged"
We can remove the XXX comments here.

2020-05-04 17:27 UTC, rehandalal commented
bors r=@mythmon

2020-05-04 17:31 UTC, merged