Recipe Timeline
mozilla-extensions/normandy-devtools pull request #25
Opened 2019-11-22 23:01 UTC by mythmon

I added a new page, and in doing so made a base component for new pages. That new page is a timeline of events for a recipe. I've been wanting to make this kind of thing to automate the analysis I did in mozilla/normandy#2040. The devtools seemed like a good place to do it.

2019-11-26 02:38 UTC, rehandalal requested changes

2019-11-26 02:38 UTC, rehandalal commented on extension/content/components/pages/AddonStudiesPage.js
> +import BasePage from "./BasePage";
nit: use absolute import path

2019-11-26 02:38 UTC, rehandalal commented on extension/experiments/normandy/api.js
> +            throw new Error("Incompatible version of Normandy");
👏🏽 one thing i'd love to look at as we grow this addon is regression testing against nightly to catch stuff like this early.

2019-11-26 02:38 UTC, rehandalal commented on .eslintrc.js
> +    "generator-star-spacing": "off",
can we pick something for a consistent spacing of the star rather than turning this off?

2019-11-26 02:38 UTC, rehandalal commented on .eslintrc.js
> +    "generator-star-spacing": "off",
i think im slightly partial to `both`

2019-11-26 02:38 UTC, rehandalal commented on extension/content/components/pages/AddonStudiesPage.js
> +export default class PrefStudiesPage extends BasePage {
the official take on inheritance: https://reactjs.org/docs/composition-vs-inheritance.html

2019-11-26 02:38 UTC, rehandalal commented on extension/content/components/pages/RecipesPage.js
> +import BaseApiPage from "./BaseApiPage";
nit: no relative import paths

2019-11-26 02:38 UTC, rehandalal commented on extension/content/components/recipes/RecipeTimeline.js
> +import "./RecipeTimeline.less";
nit: use absolute

2019-11-26 17:18 UTC, mythmon commented on .eslintrc.js
> +    "generator-star-spacing": "off",
Prettier (from `extends: [..., "plugin:prettier/recommended"]`) handles generator star spacing. This is just getting ESLint to stop fighting with it. This ESLint rule should have been disabled by the ESLint/Prettier integration, I'm not sure why it wasn't.

2019-11-26 17:18 UTC, mythmon commented on extension/content/components/pages/AddonStudiesPage.js
> +export default class PrefStudiesPage extends BasePage {
I'll switch it over.

2019-11-26 17:19 UTC, mythmon reviewed
Ack, sorry about the relative imports. VSCode has some very handy automatic import logic, but it's sort of invisible and it makes relative imports. I'll clean those up.

2020-01-24 23:24 UTC, mythmon commented
This is sort of ready to go. If you have time to review it, go for it. I think I might split this into two PRs though, one for the basepage stuff and one for the timeline page. I think that will make things simpler overall.

2020-02-20 00:10 UTC, mythmon commented
I'm actually going to abandon this. I don't think it's worth fixing the merge conflicts and cleaning this up. I think the idea of a common base page is a good idea though. That's probably something for the editing refactor though. I think the idea of a base page is something we should use in the future.

2020-02-20 00:10 UTC, closed without merging