Fix code editors on import form
mozilla-extensions/normandy-devtools pull request #661
Opened 2021-01-04 06:11 UTC by rehandalal

Fixes #594.

r?

2021-01-04 19:25 UTC, mythmon requested changes
The problem still happens for me on web+normandy://prod/recipes/import/firefox-diagnostic-experiment with this patch applied, but not all the time. I can get it to work if I navigate through the in-page address bar, but if I do a full browser navigation or refresh the page, it breaks again.

2021-01-04 20:18 UTC, rehandalal commented
Yeah sorry I found that earlier today and fixed but hadn't pushed up the commit

2021-01-06 20:33 UTC, mythmon commented
That did the trick

bors merge

2021-01-06 20:33 UTC, mythmon approved these changes

2021-01-06 20:36 UTC, merged