added console log args
mozilla-extensions/normandy-devtools pull request #86
Opened 2020-04-13 03:06 UTC by tiftran

2020-04-21 05:24 UTC, tiftran commented
my second attempt given the new actionargument json editor?

2020-04-23 19:24 UTC, rehandalal requested changes
this looks great! couple little nits.

i'm just going to pull this down and make sure it works as expected but I'm sure it will.

nice work!

2020-04-23 19:24 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/ConsoleLog.js
> +};
this isn't needed anymore

2020-04-23 19:24 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/ConsoleLog.js
> +import {
nit: new line

2020-04-23 19:33 UTC, rehandalal commented
Oh and we probably want to use the `InputField` from #105

2020-04-23 20:02 UTC, rehandalal approved these changes
small nit but r+wc

bors delegate+

2020-04-23 20:02 UTC, rehandalal commented on extension/content/components/recipes/form/arguments/ConsoleLog.js
> +import InputField from "devtools/components/recipes/form/arguments/fields/InputField";
nit: new line between module and application imports

2020-04-23 20:51 UTC, tiftran commented
bors r+

2020-04-23 20:54 UTC, merged