recipeEditor to be able to import from experimenter
mozilla-extensions/normandy-devtools pull request #87
Opened 2020-04-16 00:16 UTC by tiftran

2020-04-16 00:20 UTC, jaredlockhart commented
I remember when I spent a summer building the first version of this to import from Experimenter into 'Normandy Admin', as it was called in the day.  Poor PR got sent off on an ice float to live alone with the polar bears, never to be seen again.  We've come so far.  Super stoked for this @tiftran, thanks! 😄

2020-04-20 20:24 UTC, rehandalal requested changes
Nice job! 

Just a little refactor needed on the API stuff.

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/normandyApi.js
> +export default class NormandyAPI extends Api {
nit: you need a newline after imports

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/experimenterApi.js
> +export default class ExperimenterAPI extends Api {
nit: new line

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/experimenterApi.js
> +  async request({ url, extraHeaders, ...options }) {
nit: new line between functions

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/api.js
> +  getBaseUrl() {
nit: new line between functions

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/normandyApi.js
> +    const settings = super.formatHeaders({ extraHeaders, ...options });
this should also probably be `this`?

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/api.js
> +  }
i dont think we need this function this should continue to be in `request`

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/api.js
> -export default class NormandyAPI {
Here's what I think this file should look like:

```diff
--- a/extension/content/utils/api.js
+++ b/extension/content/utils/api.js
@@ -1,26 +1,50 @@
-export default class Api {
+export default class API {
   constructor(environment) {
     this.environment = environment;
   }
+
   getBaseUrl() {
     throw new Error("getBaseURL() needs to be implemented");
   }
 
-  formatHeaders({ extraHeaders, ...options }) {
+  async request({ url, extraHeaders, version, ...options }) {
     const headers = new Headers();
     headers.append("Accept", "application/json");
     if (!(options.body && options.body instanceof FormData)) {
       headers.append("Content-Type", "application/json");
     }
-    return {
+
+    for (let headerName in extraHeaders) {
+      headers.append(headerName, extraHeaders[headerName]);
+    }
+
+    const settings = {
       headers,
       method: "GET",
       ...options,
     };
-  }
 
-  async request(url, settings) {
-    const response = await fetch(url, settings);
+    const apiUrl = new URL(url, this.getBaseUrl({ version, ...settings }));
+
+    if ("data" in settings) {
+      if ("body" in settings) {
+        throw new Error(
+          "Only pass one of `settings.data` and `settings.body`.",
+        );
+      }
+
+      if (["GET", "HEAD"].includes(settings.method.toUpperCase())) {
+        Object.entries(settings.data).forEach(([key, value]) => {
+          apiUrl.searchParams.append(key, value);
+        });
+      } else {
+        settings.body = JSON.stringify(settings.data);
+      }
+
+      delete settings.data;
+    }
+
+    const response = await fetch(apiUrl, settings);
 
     if (!response.ok) {
       let message;
```

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/experimenterApi.js
> +import Api from "devtools/utils/api";
Changes here with changes to `api.js`:
```diff
--- a/extension/content/utils/experimenterApi.js
+++ b/extension/content/utils/experimenterApi.js
@@ -1,12 +1,8 @@
-import Api from "devtools/utils/api";
-export default class ExperimenterAPI extends Api {
-  getBaseUrl() {
-    return new URL("api/v1/", this.environment.experimenterUrl).href;
-  }
-  async request({ url, extraHeaders, ...options }) {
-    const apiUrl = new URL(url, this.getBaseUrl());
-    const settings = super.formatHeaders({ extraHeaders, ...options });
-    return super.request(apiUrl, settings);
+import API from "devtools/utils/api";
+
+export default class ExperimenterAPI extends API {
+  getBaseUrl({ version = 1 }) {
+    return new URL(`api/v${version}/`, this.environment.experimenterUrl).href;
   }
 
   async fetchRecipe(slug) {

```

2020-04-20 20:24 UTC, rehandalal commented on extension/content/utils/normandyApi.js
> +import Api from "devtools/utils/api";
And this one, after changes to `api.js`:
```diff
--- a/extension/content/utils/normandyApi.js
+++ b/extension/content/utils/normandyApi.js
@@ -1,54 +1,35 @@
-import Api from "devtools/utils/api";
-export default class NormandyAPI extends Api {
+import API from "devtools/utils/api";
+
+export default class NormandyAPI extends API {
   constructor(environment, auth) {
     super(environment);
     this.auth = auth;
   }
 
-  getBaseUrl({ version = 3, mode }) {
-    const base =
-      mode.toLowerCase() === "w"
-        ? this.environment.writeableUrl
-        : this.environment.readOnlyUrl;
-
+  getBaseUrl({ version = 3, method }) {
+    const isReadOperation = ["GET", "HEAD"].includes(method.toUpperCase());
+    const base = isReadOperation
+      ? this.environment.readOnlyUrl
+      : this.environment.writeableUrl;
     return new URL(`api/v${version}/`, base).href;
   }
 
-  async request({ version = 3, url, extraHeaders, ...options }) {
-    const settings = super.formatHeaders({ extraHeaders, ...options });
-
-    const isReadOperation = ["GET", "HEAD"].includes(
-      settings.method.toUpperCase(),
-    );
-    const mode = isReadOperation ? "r" : "w";
-    const apiUrl = new URL(url, this.getBaseUrl({ version, mode }));
+  async request(options) {
+    const { method } = options;
+    const isReadOperation = ["GET", "HEAD"].includes(method.toUpperCase());
 
+    const normandyHeaders = [];
     if (!isReadOperation) {
-      settings.headers.append(
+      normandyHeaders.append(
         "Authorization",
         `Bearer  ${this.auth.result.accessToken}`,
       );
     }
 
-    if ("data" in settings) {
-      if ("body" in settings) {
-        throw new Error(
-          "Only pass one of `settings.data` and `settings.body`.",
-        );
-      }
-
-      if (isReadOperation) {
-        Object.entries(settings.data).forEach(([key, value]) => {
-          apiUrl.searchParams.append(key, value);
-        });
-      } else {
-        settings.body = JSON.stringify(settings.data);
-      }
-
-      delete settings.data;
-    }
-
-    return super.request(apiUrl, settings);
+    return this.request({
+      ...options,
+      extraHeaders: [...options.extraHeaders, ...normandyHeaders],
+    });
   }
 
   fetchRecipePage(page, searchParams = {}) {
```

2020-04-20 22:04 UTC, rehandalal commented
just gotta get master merged in to this

2020-04-20 23:40 UTC, rehandalal commented on extension/content/components/recipes/RecipeEditor.js
> +        </FormGroup>
I'd rather see this field disappear altogether on non-import pages than just be hidden

2020-04-21 00:12 UTC, rehandalal approved these changes
THANK YOU!! GREAT WORK! 👏🏽

bors r+

2020-04-21 00:14 UTC, merged